global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "app"
    ec2_sd_configs:
      - region: ap-south-1
        port: 8000
        filters:
          - name: "tag:Name"
            values: ["url-shortener-dev-app"]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: "${1}:8000"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]